### PR TITLE
#1 iOS Target Needed

### PR DESCRIPTION
**Pull request by dcilia**
Modified the build settings to make the framework cross platform - supporting ```iOS```, ```tvOS``` & ```watchOS```.

I got the tests working on all platforms except ```watchOS``` (which currently does not support unit tests).

### CODE REVIEW

**Comment by dcilia** [comment]
Here is the exact error message I get:

```
Showing Recent Errors Only
Test target RSParserTests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
```

**Review by danielpunkass — CHANGES_REQUESTED** [review]
Thanks for tackling this problem! Looking at the diffs it seems to achieve the goal of tweaking the settings and source files to get the target building for iOS, but I wonder if it can be done with less disruptive changes to the project file? It looks as though possible there was some experimentation that got captured by Xcode, resulting in new file reference IDs for many items? If you started from scratch and applied just the build setting changes, and the tweak to RSHTMLMetdata.h and unit test files, I wonder if it will leave the project.pbxproj less mutated?

**Comment by dcilia** [comment]
No problem!  I did do some experimentation as you commented.  I will try a fresh branch and see what I come up with.

**Comment by dcilia** [comment]
Hey @danielpunkass - off of latest ```master``` when opening the ```RSParser.xcodeproj``` I am not seeing any schemes.  Is this intentional or an issue on my end?

**Comment by danielpunkass** [comment]
@dcilia I suspect that @brentsimmons never added any shared schemes to the project when he committed it. In this scenario I think Xcode will just default to inferring de facto scheme based on the .xcodeproj's first target.

Whether we want or need a scheme is probably a separate question, so wouldn't worry about it in terms of this issue unless it becomes apparent that you need a scheme to address the problem. I think the pertinent settings should be in the target, though.

**Pull request closed without merging**
