### PR TITLE
Simplify code signing

### PR DESCRIPTION
**Pull request by 0xced**
If all open source projects promote this technique of setting the development team in Xcode custom paths', everybody will be able to easily compile open source projects without having to tweak project files.

### CODE REVIEW

**Comment by kielgillard** [comment]
If you're using a Personal Team, you have to remove the iCloud entitlement on the app target. So for some, there's no easy way to avoid tweaking project files.

**Comment by 0xced** [comment]
I'm not sure what you are talking about. The RSParser project includes two targets: `RSParser` (com.apple.product-type.framework) and `RSParserTests` (com.apple.product-type.bundle.unit-test). None of them are app targets that needs tweaking entitlements.

**Comment by 0xced** [comment]
@vincode-io Would you mind to elaborate why you closed this issue?

**Comment by vincode-io** [comment]
@0xced It got automatically closed when we renamed `master` to `main`.  I didn't do it manually or for any particular reason.

Please resubmit your pull request against `main` and I will review it for merging.  Sorry for any confusion.

**Comment by 0xced** [comment]
Thanks for the explanation, Maurice. Will do once I'm in front of a computer instead of a mobile phone.

**Pull request closed without merging**
