### PR TITLE
Issue #20 - Adds Cocoapods support

### PR DESCRIPTION
**Pull request by dcilia**
This pull request adds Cocoapods support.

Additionally tested and working with ```carthage``` as well.

I pushed a tag called ```0.0.1```.

to test:

``` Ruby
target 'Foo' do
  use_frameworks!
  platform :ios, '11'

  # Pods for Foo
  pod 'RSParser', :git => 'git@github.com:dcilia/RSParser.git', :branch => 'issue_20'

  target 'FooTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Carthage:
```
$ carthage build --no-skip-current
```

or add to your ```Cartfile```

```
github "dcilia/RSParser" "issue_20"
```

### CODE REVIEW

**Comment by brentsimmons** [comment]
I’d definitely like to add Cocoapod support. But I notice that a whole bunch of files are being moved in this pull request. Is the new location a requirement of Cocoapod support? (Because I’d rather not move them if we don’t have to.)

**Comment by dcilia** [comment]
Not a requirement for Cocoapods - but there is a line in the pod spec to specify your source code locations.  I thought it would be a bit cleaner that all the source files were inside of a ```Sources``` folder (the actual tree structure has not changed, just that I grouped them inside of Sources).  Additionally, if you want to add Swift Package Manager support at a later time, the ```Sources``` folder structure is a requirement.

Feel free to make changes or close this if you want to tackle at a later time 👍

**Comment by brentsimmons** [comment]
I totally did not know about the `Sources` requirement for the Swift Package Manager (which I do want to support).

**Comment by brentsimmons** [comment]
Thanks for doing this!

I just merged, and then I updated the podspec. Would you check to make sure I updated the spec correctly?

**Comment by dcilia** [comment]
@brentsimmons looks good - except I have a typo in there - we should remove 

```s.platforms```

```
s.homepage     = "https://github.com/brentsimmons/RSParser"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author             = { "Brent Simmons" => "brent@ranchero.com" }

  s.platforms

  #  When using multiple platforms
  s.ios.deployment_target = "9.3"
  s.osx.deployment_target = "10.10"
  s.watchos.deployment_target = "2.0"
  s.tvos.deployment_target = "9.0"
```

**Comment by dcilia** [comment]
also, need to to push the tag ```0.0.1``` or, update the ```podspec``` version and push the appropriate tag. 👍

**Comment by dcilia** [comment]
When you run ```$ pod spec lint``` in terminal and you get a valid output (including pushing the tag) I believe you can simply push to the pod spec repo by following:

How do I update an existing Pod?
```
Create your Podspec as described above.
Run pod spec lint to check for errors.
Submit your Podspec to Trunk with pod trunk push NAME.podspec
```

see 
https://guides.cocoapods.org/making/specs-and-specs-repo.html

**Pull request merged**
